<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Selenium Utilities" duration-ms="54460" started-at="2019-07-30T20:27:20Z" finished-at="2019-07-30T20:28:14Z">
    <groups>
    </groups>
    <test name="Free CRM App Test Cases" duration-ms="54460" started-at="2019-07-30T20:27:20Z" finished-at="2019-07-30T20:28:14Z">
      <class name="com.qa.tests.SampleTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.qa.tests.SampleTest@7cd62f43]" name="beforeTest" is-config="true" duration-ms="2589" started-at="2019-07-30T20:27:20Z" finished-at="2019-07-30T20:27:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="firstTest()[pri:0, instance:com.qa.tests.SampleTest@7cd62f43]" name="firstTest" duration-ms="2999" started-at="2019-07-30T20:27:22Z" finished-at="2019-07-30T20:27:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method status="PASS" signature="secondTest()[pri:0, instance:com.qa.tests.SampleTest@7cd62f43]" name="secondTest" duration-ms="1774" started-at="2019-07-30T20:27:25Z" finished-at="2019-07-30T20:27:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondTest -->
        <test-method status="FAIL" signature="thirdTest()[pri:0, instance:com.qa.tests.SampleTest@7cd62f43]" name="thirdTest" duration-ms="46772" started-at="2019-07-30T20:27:27Z" finished-at="2019-07-30T20:28:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [XYZ] but found [TestNG Listeners in Selenium: ITestListener & ITestResult Example]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [XYZ] but found [TestNG Listeners in Selenium: ITestListener & ITestResult Example]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.tests.SampleTest.thirdTest(SampleTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.qa.tests.SampleTest@7cd62f43]" name="afterTest" is-config="true" duration-ms="296" started-at="2019-07-30T20:28:14Z" finished-at="2019-07-30T20:28:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.qa.tests.SampleTest -->
    </test> <!-- Free CRM App Test Cases -->
  </suite> <!-- Selenium Utilities -->
</testng-results>
